# Generated by Django 5.2.6 on 2025-09-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reg_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
                ('cpassword', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
