# Generated by Django 5.2.6 on 2025-09-25 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsapp', '0002_reg_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('canceled', 'Canceled'), ('rescheduled', 'Rescheduled')], default='booked', max_length=20)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='amsapp.slot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amsapp.reg_tbl')),
            ],
        ),
    ]
