# Generated by Django 5.2.6 on 2025-09-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsapp', '0003_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_tbl',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
